/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryFortune = IDL.Record({
  'score' : IDL.Nat,
  'message' : IDL.Text,
});
export const LuckReading = IDL.Record({
  'finance' : CategoryFortune,
  'luckyNumber' : IDL.Nat,
  'overallMessage' : IDL.Text,
  'luckyColor' : IDL.Text,
  'love' : CategoryFortune,
  'luckyTimeOfDay' : IDL.Text,
  'career' : CategoryFortune,
  'health' : CategoryFortune,
});

export const idlService = IDL.Service({
  'getTodaysLuck' : IDL.Func([], [LuckReading], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryFortune = IDL.Record({
    'score' : IDL.Nat,
    'message' : IDL.Text,
  });
  const LuckReading = IDL.Record({
    'finance' : CategoryFortune,
    'luckyNumber' : IDL.Nat,
    'overallMessage' : IDL.Text,
    'luckyColor' : IDL.Text,
    'love' : CategoryFortune,
    'luckyTimeOfDay' : IDL.Text,
    'career' : CategoryFortune,
    'health' : CategoryFortune,
  });
  
  return IDL.Service({
    'getTodaysLuck' : IDL.Func([], [LuckReading], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };